id: AE6BF8FA2
base_file: f5433.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:59:03.530132
  last_modified_at: 2022-06-05 19:59:03.530136
