id: AE6BF8FA2
base_file: fD85C.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:59:03.540021
  last_modified_at: 2022-06-05 19:59:03.540027
