id: AE6BF8FA2
base_file: fD249.txt
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:59:03.536695
  last_modified_at: 2022-06-05 19:59:03.536699
