id: AE6BF8FA2
base_file: f82C8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:59:03.533620
  last_modified_at: 2022-06-05 19:59:03.533624
