id: AE6BF8FA2
base_file: f5208.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 19:59:03.528562
  last_modified_at: 2022-06-05 19:59:03.528565
